"""update risk assessments, remove decision column

Revision ID: 384bf1f72774
Revises: 71aedf6b7857
Create Date: 2025-08-16 01:11:59.836052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '384bf1f72774'
down_revision: Union[str, Sequence[str], None] = '71aedf6b7857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_assessments_decision'), table_name='risk_assessments')
    op.drop_column('risk_assessments', 'decision')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_assessments', sa.Column('decision', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_risk_assessments_decision'), 'risk_assessments', ['decision'], unique=False)
    # ### end Alembic commands ###
