"""update risk assessments, add expires_at column

Revision ID: 38bd0fa29699
Revises: 384bf1f72774
Create Date: 2025-08-16 01:19:47.448552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38bd0fa29699'
down_revision: Union[str, Sequence[str], None] = '384bf1f72774'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_assessments', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_assessments', 'expires_at')
    # ### end Alembic commands ###
