"""update credit_offer; nullable fields

Revision ID: f405ae2d2dca
Revises: 38bd0fa29699
Create Date: 2025-08-18 22:33:28.822384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f405ae2d2dca'
down_revision: Union[str, Sequence[str], None] = '38bd0fa29699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credit_offers', 'credit_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('credit_offers', 'credit_limit',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('credit_offers', 'apr',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credit_offers', 'apr',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.alter_column('credit_offers', 'credit_limit',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('credit_offers', 'credit_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
